services:
  - type: web
    name: fundiq-backend
    rootDir: ./backend
    env: python
    runtime: python3
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    plan: free
